theme: jekyll-theme-slate

include:
- _audio_effect_2_c_make_lists_8txt.html
- _audio_effect_8cpp.html
- _audio_effect_8cpp__incl.map
- _audio_effect_8cpp__incl.md5
- _audio_effect_8cpp__incl.png
- _audio_effect_8h.html
- _audio_effect_8h__dep__incl.dot
- _audio_effect_8h__dep__incl.map
- _audio_effect_8h__dep__incl.md5
- _audio_effect_8h__dep__incl.png
- _audio_effect_8h__incl.map
- _audio_effect_8h__incl.md5
- _audio_effect_8h__incl.png
- _audio_effect_8h_source.html
- _audio_effect_biquad_8cpp.html
- _audio_effect_biquad_8cpp__incl.dot
- _audio_effect_biquad_8cpp__incl.map
- _audio_effect_biquad_8cpp__incl.md5
- _audio_effect_biquad_8cpp__incl.png
- _audio_effect_biquad_8h.html
- _audio_effect_biquad_8h__dep__incl.map
- _audio_effect_biquad_8h__dep__incl.md5
- _audio_effect_biquad_8h__dep__incl.png
- _audio_effect_biquad_8h__incl.dot
- _audio_effect_biquad_8h__incl.map
- _audio_effect_biquad_8h__incl.md5
- _audio_effect_biquad_8h__incl.png
- _audio_effect_biquad_8h_source.html
- _audio_effect_compressor_8cpp.html
- _audio_effect_compressor_8cpp__incl.map
- _audio_effect_compressor_8cpp__incl.md5
- _audio_effect_compressor_8cpp__incl.png
- _audio_effect_compressor_8h.html
- _audio_effect_compressor_8h__dep__incl.map
- _audio_effect_compressor_8h__dep__incl.md5
- _audio_effect_compressor_8h__dep__incl.png
- _audio_effect_compressor_8h__incl.map
- _audio_effect_compressor_8h__incl.md5
- _audio_effect_compressor_8h__incl.png
- _audio_effect_compressor_8h_source.html
- _audio_effect_delay_8cpp.html
- _audio_effect_delay_8cpp__incl.map
- _audio_effect_delay_8cpp__incl.md5
- _audio_effect_delay_8cpp__incl.png
- _audio_effect_delay_8h.html
- _audio_effect_delay_8h__dep__incl.map
- _audio_effect_delay_8h__dep__incl.md5
- _audio_effect_delay_8h__dep__incl.png
- _audio_effect_delay_8h__incl.map
- _audio_effect_delay_8h__incl.md5
- _audio_effect_delay_8h__incl.png
- _audio_effect_delay_8h_source.html
- _audio_effect_distortion_8cpp.html
- _audio_effect_distortion_8cpp__incl.map
- _audio_effect_distortion_8cpp__incl.md5
- _audio_effect_distortion_8cpp__incl.png
- _audio_effect_distortion_8h.html
- _audio_effect_distortion_8h__dep__incl.dot
- _audio_effect_distortion_8h__dep__incl.map
- _audio_effect_distortion_8h__dep__incl.md5
- _audio_effect_distortion_8h__dep__incl.png
- _audio_effect_distortion_8h__incl.map
- _audio_effect_distortion_8h__incl.md5
- _audio_effect_distortion_8h__incl.png
- _audio_effect_distortion_8h_source.html
- _audio_effect_gain_8cpp.html
- _audio_effect_gain_8cpp__incl.map
- _audio_effect_gain_8cpp__incl.md5
- _audio_effect_gain_8cpp__incl.png
- _audio_effect_gain_8h.html
- _audio_effect_gain_8h__dep__incl.map
- _audio_effect_gain_8h__dep__incl.md5
- _audio_effect_gain_8h__dep__incl.png
- _audio_effect_gain_8h__incl.map
- _audio_effect_gain_8h__incl.md5
- _audio_effect_gain_8h__incl.png
- _audio_effect_gain_8h_source.html
- _audio_effect_pan_8cpp.html
- _audio_effect_pan_8cpp__incl.map
- _audio_effect_pan_8cpp__incl.md5
- _audio_effect_pan_8cpp__incl.png
- _audio_effect_pan_8h.html
- _audio_effect_pan_8h__dep__incl.map
- _audio_effect_pan_8h__dep__incl.md5
- _audio_effect_pan_8h__dep__incl.png
- _audio_effect_pan_8h__incl.map
- _audio_effect_pan_8h__incl.md5
- _audio_effect_pan_8h__incl.png
- _audio_effect_pan_8h_source.html
- _audio_file_8cpp.html
- _audio_file_8cpp__incl.map
- _audio_file_8cpp__incl.md5
- _audio_file_8cpp__incl.png
- _audio_file_8h.html
- _audio_file_8h.js
- _audio_file_8h__dep__incl.map
- _audio_file_8h__dep__incl.md5
- _audio_file_8h__dep__incl.png
- _audio_file_8h__incl.map
- _audio_file_8h__incl.md5
- _audio_file_8h__incl.png
- _audio_file_8h_source.html
- _audio_file_i_o_2_c_make_lists_8txt.html
- _audio_file_if_8cpp.html
- _audio_file_if_8cpp__incl.map
- _audio_file_if_8cpp__incl.md5
- _audio_file_if_8cpp__incl.png
- _audio_file_if_8h.html
- _audio_file_if_8h__dep__incl.map
- _audio_file_if_8h__dep__incl.md5
- _audio_file_if_8h__dep__incl.png
- _audio_file_if_8h__incl.map
- _audio_file_if_8h__incl.md5
- _audio_file_if_8h__incl.png
- _audio_file_if_8h_source.html
- _audio_fx_framework_exec_2_c_make_lists_8txt.html
- _audio_fx_framework_exec_8cpp.html
- _audio_fx_framework_exec_8cpp.js
- _audio_fx_framework_exec_8cpp__incl.dot
- _audio_fx_framework_exec_8cpp__incl.map
- _audio_fx_framework_exec_8cpp__incl.md5
- _audio_fx_framework_exec_8cpp__incl.png
- _lfo_8h.html
- _lfo_8h.js
- _lfo_8h__dep__incl.map
- _lfo_8h__dep__incl.md5
- _lfo_8h__dep__incl.png
- _lfo_8h__incl.map
- _lfo_8h__incl.md5
- _lfo_8h__incl.png
- _lfo_8h_source.html
- _r_e_a_d_m_e_8md.html
- _ring_buffer_8h.html
- _ring_buffer_8h__dep__incl.dot
- _ring_buffer_8h__dep__incl.map
- _ring_buffer_8h__dep__incl.md5
- _ring_buffer_8h__dep__incl.png
- _ring_buffer_8h__incl.map
- _ring_buffer_8h__incl.md5
- _ring_buffer_8h__incl.png
- _ring_buffer_8h_source.html
- _synthesis_8h.html
- _synthesis_8h.js
- _synthesis_8h__dep__incl.map
- _synthesis_8h__dep__incl.md5
- _synthesis_8h__dep__incl.png
- _synthesis_8h__incl.map
- _synthesis_8h__incl.md5
- _synthesis_8h__incl.png
- _synthesis_8h_source.html
- _test_8cpp.html
- _test_8cpp.js
- _test_8cpp__incl.map
- _test_8cpp__incl.md5
- _test_8cpp__incl.png
- _test___audio_effect_biquad_8cpp.html
- _test___audio_effect_biquad_8cpp__incl.map
- _test___audio_effect_biquad_8cpp__incl.md5
- _test___audio_effect_biquad_8cpp__incl.png
- _test___audio_effect_compressor_8cpp.html
- _test___audio_effect_compressor_8cpp__incl.map
- _test___audio_effect_compressor_8cpp__incl.md5
- _test___audio_effect_compressor_8cpp__incl.png
- _test___audio_effect_delay_8cpp.html
- _test___audio_effect_delay_8cpp__incl.map
- _test___audio_effect_delay_8cpp__incl.md5
- _test___audio_effect_delay_8cpp__incl.png
- _test___audio_effect_distortion_8cpp.html
- _test___audio_effect_distortion_8cpp__incl.map
- _test___audio_effect_distortion_8cpp__incl.md5
- _test___audio_effect_distortion_8cpp__incl.png
- _test___audio_effect_gain_8cpp.html
- _test___audio_effect_gain_8cpp__incl.map
- _test___audio_effect_gain_8cpp__incl.md5
- _test___audio_effect_gain_8cpp__incl.png
- _test___audio_effect_pan_8cpp.html
- _test___audio_effect_pan_8cpp__incl.map
- _test___audio_effect_pan_8cpp__incl.md5
- _test___audio_effect_pan_8cpp__incl.png
- _test___audio_i_o_8cpp.html
- _test___audio_i_o_8cpp__incl.map
- _test___audio_i_o_8cpp__incl.md5
- _test___audio_i_o_8cpp__incl.png
- _tests_2_test_exec_2_c_make_lists_8txt.html
- _util_8h.html
- _util_8h__dep__incl.map
- _util_8h__dep__incl.md5
- _util_8h__dep__incl.png
- _util_8h__incl.map
- _util_8h__incl.md5
- _util_8h__incl.png
- _util_8h_source.html
- _vector_8h.html
- _vector_8h__dep__incl.map
- _vector_8h__dep__incl.md5
- _vector_8h__dep__incl.png
- _vector_8h__incl.map
- _vector_8h__incl.md5
- _vector_8h__incl.png
- _vector_8h_source.html
